# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f39d859a2fee67c88ee003d46c888cda039105c5bdf94b3e3464e7d06a8ed51d43116ce060c4573ff6719fe3e1d410a37a30855ada4fb8050a36e65843d4575

test:
  secret_key_base: 7f0f5b05e90996b070a295e0e9c2ce3a948415dcae06b5b56447dbde173d300ac0a563227515d17b5d7a64670882a1b76af7c77084a1070fa9cebda587422809

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
